name: "CapRover Deploy Token & Image"
description: "Action to deploy on Caprover server"
author: "Johannes Ronski"
branding:
  icon: upload-cloud
  color: orange
inputs:
  server:
    description: "CapRover admin panel URL. Ex. https://captain.root.domain.com"
    required: true
  token:
    description: 'CapRover application token. Use $\{{ secrets.CAPROVER_TOKEN }} for better security.'
    required: false
  password:
    description: 'CapRover application password. Use $\{{ secrets.CAPROVER_PASSWORD }} for better security.'
    required: false
  appname:
    description: "Application name on the CapRover server. Must exists."
    required: true
  image:
    description: "Image name which will be deployed"
    required: false
  tar:
    description: "Tar file which will be deployed"
    required: false
  branch:
    description: "Branch which will be deployed"
    required: false
  deploy_check_wait_time:
    description: "Time to check for deployment status"
    default: "30"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
