#!/bin/sh

#setting envs
export CAPROVER_URL=$INPUT_SERVER
export CAPROVER_PASSWORD=$INPUT_PASSWORD
export CAPROVER_APP=$INPUT_APPNAME
export CAPROVER_TAR_FILE=$INPUT_TAR
export CAPROVER_IMAGE_NAME=$INPUT_IMAGE
export CAPROVER_APP_TOKEN=$INPUT_TOKEN
export CAPROVER_BRANCH=$INPUT_BRANCH

caprover deploy