#!/bin/sh

#setting envs
export CAPROVER_URL=$INPUT_SERVER
test $INPUT_PASSWORD && export CAPROVER_PASSWORD=$INPUT_PASSWORD
export CAPROVER_APP=$INPUT_APPNAME
test $INPUT_TAR && export CAPROVER_TAR_FILE=$INPUT_TAR
test $INPUT_IMAGE && export CAPROVER_IMAGE_NAME=$INPUT_IMAGE
test $INPUT_TOKEN && export CAPROVER_APP_TOKEN=$INPUT_TOKEN
test $INPUT_BRANCH && export CAPROVER_BRANCH=$INPUT_BRANCH

caprover deploy